services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel  run
    env_file:
      - ~/homelab/.env
    networks:
      - proxy
      - homepage
      - watchtower
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Development"
      - "homepage.icon=cloudflare.png"
      - "homepage.name=Cloudflare"
      - "homepage.description=Tunnel"
    security_opt:
      - no-new-privileges:true


