---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Server Dashboard

theme: dark
color: slate

background:
  opacity: 5

layout:
  Applications:
    style: row
    columns: 4

  Development:
    style: row
    columns: 4

  Network:
    style: row
    columns: 4

  Security:
    style: row
    columns: 4

  Tools:
    style: row
    columns: 4

  Maintenance:
    style: row
    columns: 4
